version: "3"
services:
  flask:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgresql/postgres
      ENV: ${ENV}
      TZ: Asia/Tokyo
    volumes:
      - ./app/back:/app/back
    tty: true
