services:
  flask:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      ENV: ${ENV}
      DATABASE_URI: ${DATABASE_URI}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      TZ: Asia/Tokyo
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./app/back:/app/back
      - ./app/front/out:/app/front/out
    tty: true
